//Declarative
pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        echo "Building ..."
        sh 'date > log.txt'
        archiveArtifacts artifacts: '*.txt', fingerprint: true, followSymlinks: false
      }
    }
    stage('Test') {
      steps {
        echo "Testing ..."
      }
    }
    stage('Deploy') {
      steps {
        echo "Deploying ..."
      }
    }
  }
}
