pipeline {
    agent any 
    stages {
        stage('Stage 1') {
            steps {
                echo 'Hello world from Jenkinsfile written in Declarative syntax' 
            }
        }
    }
}
