node {
  checkout scm
  stage('Build') {
    echo "Building ..."
    sh 'pwd; ls > log.txt'
    archiveArtifacts artifacts: '*.txt', fingerprint: true, followSymlinks: false
  }
  stage('Test') {
    echo "Testing ..."
  }
  stage('Deploy') {
    echo "Deploying ..."
  }
}
