node {
  checkout scm
  stage('Build') {
    echo "Building ..."
    sh 'pwd; ls > log.txt'
    archiveArtifacts artifacts: '*.txt', fingerprint: true, followSymlinks: false
  }
  stage('Test') {
    echo "Testing ..."
    sh 'test -f /tmp/'
    sh 'test -f log.txt'
  }
  stage('Deploy') {
    echo "Deploying ..."
  }
}
